In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
dataset = pd.read_csv('./dataset/creditcard.csv')
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
dataset.shape

(284807, 31)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
amount = dataset['Amount'].values
dataset['Amount'] = sc.fit_transform(amount.reshape(-1, 1))
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28    Amount  Class  
0 -0.189115  0.133558 -0.021053  0.244964      0  
1  0.125895 -0.008983  0.014724 -0.342475      0  
2 -0.139097 -0.055353 -0.059752  1.160686      0  
3 -0.221929  0.062723  0.061458  0.140534      0  
4  0.502292  0.219422  0.215153 -0.073403      0  

[5 rows x 31 columns]

In [5]:
dataset.drop_duplicates(inplace=True)

In [6]:
dataset.shape

(283726, 31)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [9]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=2,test_size=0.25,stratify=y)

## Creating a function to test multiple model effectively

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report, f1_score
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [13]:
def mymodel(model):
    model.fit(xtrain,ytrain)
    ypred=model.predict(xtest)
    
    tr=model.score(xtrain,ytrain)
    te=model.score(xtest,ytest)
    
    print('F1 score',f1_score(ytest, ypred))
    print(str(model)[:-2],'Accuracy: ',accuracy_score(ytest,ypred),\
          '\nConfusion Matrix: \n',confusion_matrix(ytest,ypred))
    print("Classification report: \n",classification_report(ytest,ypred))
    print(f'Training Accuracy: {tr}\nTesting Accuracy: {te}')
    
    return model

In [14]:
knn=mymodel(KNeighborsClassifier())

F1 score 0.06557377049180328
KNeighborsClassifier Accuracy:  0.998392826932837 
Confusion Matrix: 
 [[70814     0]
 [  114     4]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     70814
           1       1.00      0.03      0.07       118

    accuracy                           1.00     70932
   macro avg       1.00      0.52      0.53     70932
weighted avg       1.00      1.00      1.00     70932

Training Accuracy: 0.9985149957235636
Testing Accuracy: 0.998392826932837


In [15]:
svc=mymodel(SVC())

F1 score 0.0
SVC Accuracy:  0.9983364348953928 
Confusion Matrix: 
 [[70814     0]
 [  118     0]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     70814
           1       0.00      0.00      0.00       118

    accuracy                           1.00     70932
   macro avg       0.50      0.50      0.50     70932
weighted avg       1.00      1.00      1.00     70932

Training Accuracy: 0.9983317198793199
Testing Accuracy: 0.9983364348953928


In [16]:
dt=mymodel(DecisionTreeClassifier())

F1 score 0.6978723404255319
DecisionTreeClassifier Accuracy:  0.9989990413353634 
Confusion Matrix: 
 [[70779    35]
 [   36    82]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     70814
           1       0.70      0.69      0.70       118

    accuracy                           1.00     70932
   macro avg       0.85      0.85      0.85     70932
weighted avg       1.00      1.00      1.00     70932

Training Accuracy: 1.0
Testing Accuracy: 0.9989990413353634


In [17]:
gnb=mymodel(GaussianNB())

F1 score 0.22390317700453863
GaussianNB Accuracy:  0.9927677211977669 
Confusion Matrix: 
 [[70345   469]
 [   44    74]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      0.99      1.00     70814
           1       0.14      0.63      0.22       118

    accuracy                           0.99     70932
   macro avg       0.57      0.81      0.61     70932
weighted avg       1.00      0.99      1.00     70932

Training Accuracy: 0.9932798857110633
Testing Accuracy: 0.9927677211977669


In [18]:
lr=mymodel(LogisticRegression())

F1 score 0.6725663716814159
LogisticRegression Accuracy:  0.9989567473072802 
Confusion Matrix: 
 [[70782    32]
 [   42    76]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     70814
           1       0.70      0.64      0.67       118

    accuracy                           1.00     70932
   macro avg       0.85      0.82      0.84     70932
weighted avg       1.00      1.00      1.00     70932

Training Accuracy: 0.9990319275919434
Testing Accuracy: 0.9989567473072802


## Training and testing all classification models to find the best one

In [19]:
svc=mymodel(SVC())

F1 score 0.0
SVC Accuracy:  0.9983364348953928 
Confusion Matrix: 
 [[70814     0]
 [  118     0]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     70814
           1       0.00      0.00      0.00       118

    accuracy                           1.00     70932
   macro avg       0.50      0.50      0.50     70932
weighted avg       1.00      1.00      1.00     70932

Training Accuracy: 0.9983317198793199
Testing Accuracy: 0.9983364348953928


In [20]:
lr=mymodel(LogisticRegression())

F1 score 0.6725663716814159
LogisticRegression Accuracy:  0.9989567473072802 
Confusion Matrix: 
 [[70782    32]
 [   42    76]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     70814
           1       0.70      0.64      0.67       118

    accuracy                           1.00     70932
   macro avg       0.85      0.82      0.84     70932
weighted avg       1.00      1.00      1.00     70932

Training Accuracy: 0.9990319275919434
Testing Accuracy: 0.9989567473072802


In [21]:
gnb=mymodel(GaussianNB())

F1 score 0.22390317700453863
GaussianNB Accuracy:  0.9927677211977669 
Confusion Matrix: 
 [[70345   469]
 [   44    74]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      0.99      1.00     70814
           1       0.14      0.63      0.22       118

    accuracy                           0.99     70932
   macro avg       0.57      0.81      0.61     70932
weighted avg       1.00      0.99      1.00     70932

Training Accuracy: 0.9932798857110633
Testing Accuracy: 0.9927677211977669


In [22]:
dt=mymodel(DecisionTreeClassifier())

F1 score 0.7012987012987013
DecisionTreeClassifier Accuracy:  0.9990272373540856 
Confusion Matrix: 
 [[70782    32]
 [   37    81]]
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     70814
           1       0.72      0.69      0.70       118

    accuracy                           1.00     70932
   macro avg       0.86      0.84      0.85     70932
weighted avg       1.00      1.00      1.00     70932

Training Accuracy: 1.0
Testing Accuracy: 0.9990272373540856


# Cross Validation

In [24]:
x=dataset.iloc[:10000,:-1]
y=dataset.iloc[:10000,-1]

In [25]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=2,\
                                           test_size=0.25,stratify=y)

In [34]:
from sklearn.model_selection import GridSearchCV
parameters={'C':[0.1,10],'gamma':[0.1,0.01,0.001],'kernel':['rbf']}

grid=GridSearchCV(SVC(),parameters,verbose=2)
grid.fit(xtrain,ytrain)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ..................... C=0.1, gamma=0.1, kernel=rbf, total=   3.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.1s remaining:    0.0s


[CV] ..................... C=0.1, gamma=0.1, kernel=rbf, total=   3.1s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ..................... C=0.1, gamma=0.1, kernel=rbf, total=   3.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ..................... C=0.1, gamma=0.1, kernel=rbf, total=   3.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ..................... C=0.1, gamma=0.1, kernel=rbf, total=   3.1s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .................... C=0.1, gamma=0.01, kernel=rbf, total=   1.9s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .................... C=0.1, gamma=0.01, kernel=rbf, total=   1.8s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .................... C=0.1, gamma=0.01, kernel=rbf, total=   1.8s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] .

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed:  1.7min finished


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 10], 'gamma': [0.1, 0.01, 0.001],
                         'kernel': ['rbf']},
             verbose=2)

In [35]:
grid.best_params_

{'C': 10, 'gamma': 0.001, 'kernel': 'rbf'}

In [36]:
grid.best_estimator_

SVC(C=10, gamma=0.001)

In [37]:
svm=grid.best_estimator_

In [38]:
svm.fit(xtrain,ytrain)
ypred=svm.predict(xtest)
    
tr=svm.score(xtrain,ytrain)
te=svm.score(xtest,ytest)
    
print('F1 score',f1_score(ytest, ypred))
print('Accuracy: ',accuracy_score(ytest,ypred))
print("Classification report: \n",classification_report(ytest,ypred))
print(f'Training Accuracy: {tr}\nTesting Accuracy: {te}')

F1 score 0.3636363636363636
Accuracy:  0.9972
Classification report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2491
           1       1.00      0.22      0.36         9

    accuracy                           1.00      2500
   macro avg       1.00      0.61      0.68      2500
weighted avg       1.00      1.00      1.00      2500

Training Accuracy: 1.0
Testing Accuracy: 0.9972


# SHAP

In [ ]:
import shap

In [ ]:
# explain the model's predictions using SHAP
# (same syntax works for LightGBM, CatBoost, scikit-learn, transformers, Spark, etc.)
explainer = shap.Explainer(xgb)
shap_values = explainer(X_train)

# visualize the first prediction's explanation
shap.plots.waterfall(shap_values[0])

In [ ]:
# visualize the first prediction's explanation with a force plot
shap.initjs()
shap.plots.force(shap_values[0])

In [ ]:
# visualize all the training set predictions
shap.initjs()
shap.plots.force(shap_values)

In [ ]:
# create a dependence scatter plot to show the effect of a single feature across the whole dataset
shap.plots.scatter(shap_values[:,"RM"], color=shap_values)

In [ ]:
# summarize the effects of all the features
shap.plots.beeswarm(shap_values)

In [ ]:
shap.plots.bar(shap_values)

### Model agnostic example with KernelExplainer
(explains any function)

In [ ]:
import sklearn
import shap
from sklearn.model_selection import train_test_split

# print the JS visualization code to the notebook
shap.initjs()

# train a SVM classifier
X_train,X_test,Y_train,Y_test = train_test_split(X, y, test_size = 0.3, random_state = 1,shuffle=True)
svm = sklearn.svm.SVC(kernel='rbf', probability=True)
svm.fit(X_train, Y_train)

# use Kernel SHAP to explain test set predictions
explainer = shap.KernelExplainer(svm.predict_proba, X_train, link="logit")
shap_values = explainer.shap_values(X_test, nsamples=100)

# plot the SHAP values for the Setosa output of the first instance
shap.force_plot(explainer.expected_value[0], shap_values[0][0,:], X_test.iloc[0,:], link="logit")

In [ ]:
# plot the SHAP values for the Setosa output of all instances
shap.force_plot(explainer.expected_value[0], shap_values[0], X_test, link="logit")

In [ ]:
shap.TreeExplainer(xgb).shap_interaction_values(X)