In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
dataset = pd.read_csv('./dataset/new_creditcard.csv')
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
dataset.shape

(568630, 31)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
amount = dataset['Amount'].values
dataset['Amount'] = sc.fit_transform(amount.reshape(-1, 1))
dataset.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28    Amount  Class  
0 -0.189115  0.133558 -0.021053  0.010988      0  
1  0.125895 -0.008983  0.014724 -0.492594      0  
2 -0.139097 -0.055353 -0.059752  0.795990      0  
3 -0.221929  0.062723  0.061458 -0.078534      0  
4  0.502292  0.219422  0.215153 -0.261932      0  

[5 rows x 31 columns]

In [5]:
dataset.drop_duplicates(inplace=True)

In [6]:
dataset.shape

(567549, 31)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = dataset.drop('Class', axis = 1).values
y = dataset['Class'].values

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1,shuffle=True)

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [11]:
# Decision Tree
DT = DecisionTreeClassifier(max_depth = 4, criterion = 'entropy')
DT.fit(X_train, y_train)
dt_yhat = DT.predict(X_test)

print('Accuracy score of the Decision Tree model is {}'.format(accuracy_score(y_test, dt_yhat)))
print('F1 score of the Decision Tree model is {}'.format(f1_score(y_test, dt_yhat)))
print(confusion_matrix(y_test, dt_yhat, labels = [0, 1]))

Accuracy score of the Decision Tree model is 0.997486271400464
F1 score of the Decision Tree model is 0.9974898538484999
[[84797   177]
 [  251 85040]]


In [12]:
# K-Nearest Neighbors
n = 7
KNN = KNeighborsClassifier(n_neighbors = n)
KNN.fit(X_train, y_train)
knn_yhat = KNN.predict(X_test)

print('Accuracy score of the K-Nearest Neighbors model is {}'.format(accuracy_score(y_test, knn_yhat)))
print('F1 score of the K-Nearest Neighbors model is {}'.format(f1_score(y_test, knn_yhat)))
print(confusion_matrix(y_test, knn_yhat, labels = [0, 1]))

Accuracy score of the K-Nearest Neighbors model is 0.9982967726778845
F1 score of the K-Nearest Neighbors model is 0.9982976025547702
[[84946    28]
 [  262 85029]]


In [13]:
# Logistic Regression
lr = LogisticRegression(max_iter=100)
lr.fit(X_train, y_train)
lr_yhat = lr.predict(X_test)

print('Accuracy score of the Logistic Regression model is {}'.format(accuracy_score(y_test, lr_yhat)))
print('F1 score of the Logistic Regression model is {}'.format(f1_score(y_test, lr_yhat)))
print(confusion_matrix(y_test, lr_yhat, labels = [0, 1]))

Accuracy score of the Logistic Regression model is 0.9989780636067307
F1 score of the Logistic Regression model is 0.9989799148756552
[[84891    83]
 [   91 85200]]


In [14]:
# Random Forest
rf = RandomForestClassifier(max_depth = 4)
rf.fit(X_train, y_train)
rf_yhat = rf.predict(X_test)

print('Accuracy score of the Random Forest model is {}'.format(accuracy_score(y_test, rf_yhat)))
print('F1 score of the Random Forest model is {}'.format(f1_score(y_test, rf_yhat)))
print(confusion_matrix(y_test, rf_yhat, labels = [0, 1]))

Accuracy score of the Random Forest model is 0.9992482306992042
F1 score of the Random Forest model is 0.9992499091686884
[[84878    96]
 [   32 85259]]


In [15]:
# XGBoost
xgb = XGBClassifier(max_depth = 4)
xgb.fit(X_train, y_train)
xgb_yhat = xgb.predict(X_test)

print('Accuracy score of the XGBoost model is {}'.format(accuracy_score(y_test, xgb_yhat)))
print('F1 score of the XGBoost model is {}'.format(f1_score(y_test, xgb_yhat)))
print(confusion_matrix(y_test, xgb_yhat, labels = [0, 1]))

Accuracy score of the XGBoost model is 0.9997298329075265
F1 score of the XGBoost model is 0.9997303096748473
[[84959    15]
 [   31 85260]]


In [ ]:
# Support Vector Machines
svm = SVC()
svm.fit(X_train, y_train)
svm_yhat = svm.predict(X_test)

print('Accuracy score of the upport Vector Machines model is {}'.format(accuracy_score(y_test, svm_yhat)))
print('F1 score of the upport Vector Machines model is {}'.format(f1_score(y_test, svm_yhat)))
print(confusion_matrix(y_test, svm_yhat, labels = [0, 1]))